# Generated by Django 3.1.5 on 2021-01-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(default='User Guest', max_length=30),
            preserve_default=False,
        ),
    ]
