# Generated by Django 3.1.5 on 2021-01-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='default@mail.com', max_length=254),
            preserve_default=False,
        ),
    ]
